### ISSUE TITLE
`SharedMemoryManager` singleton may need be built in main process or a individual lib when used under multiple processes or dlls

### ISSUE THREAD

**Issue by Harold2017** [kboutora/ipvar#2]
Hi kboutora,

I noticed your `SharedMemoryManager` has instance validation test in `getInstance` by using SHM name as kind of GUID, but i wonder whether is it enough for using across dll boundry?

For example, if the `SharedMemoryManager` is created in a dll and referenced in main process, but at some time, this dll was unloaded, the former valid variables may become invalid due to the instance was invalid. (I'm not sure and just want to have a discussion here.)

I did not have experience in using boost ipc module, so maybe the `managed_shared_memory` can take care of this instance creation issue?

Thanks.

**Comment by kboutora** [comment]
Hi Harold,
Assuming you are on the Windows platform:

In the scenario you are describing, both the main program and the dll will hold an instance of the singleton. DLLs have their own memory space. 

If they have both accessed the shared variable, then unloading the dll wont have any impact. 

In the scenario where the DLL creates an ipvar, then is unloaded, and only after that the main program tries to get the ipvar, then yes, it wont be here. 

You can resolve this by creating forcing the creation of a dummy variable by the executable before loading the dll.

Thanks,
Kamal

**Comment by Harold2017** [comment]
Hi kboutora,

Your thoroughness and clarity were greatly appreciated. I think persistent variable is what i need.
Thank you for your detailed explanation!

Harold
